// Generated by Wrangler
// After adding bindings to `wrangler.toml`, regenerate this interface via `npm run cf-typegen`
interface Env {
	APP_ENV: string;
	API_TOKEN: string;
	SECRET_TOKEN: string;
}
